### ISSUE TITLE
Add links to capacity self-assessments

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-effective-nodes-guidance#10]
Third paragraph of §7.3 should link to both capacity self-assessments

**Comment by dnoesgaard** [comment]
Link to online self-assessment tool for national biodiversity information facilities: https://www.gbif.org/tool/6Y2SqK8XokHUqIFUn6TLxX

Link to PDF self-assessment for data holding institutions
https://www.gbif.org/document/82785

(should the latter be turned into an online version as well?)
