### ISSUE TITLE
Deposit v2015 PDF in repo for DOI/archival purposes?

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-effective-nodes-guidance#16]
@MattBlissett can we consider depositing PDFs of the four language versions of the first edition in the GBIF repo under a metadata page? Doing so would give us a canonical reference to point to for the first version to use in the [DataCite DOI record](https://doi.org/10.15468/doc.fm4b-6q42). 

Open to other alternatives—just thought to flag it as something to resolve.

**Comment by kcopas** [comment]
PDFs are currently linked [here](https://www.gbif.org/document/80925) under 'Previous versions'

**Comment by MattBlissett** [comment]
We can; I think we can decide this once we've decided where the documents are published, where new versions will be published, and therefore what to do with the old versions.

**Comment by kcopas** [comment]
- [x] Consider whether an archived PDF should be PDF/A-compliant

**Comment by kcopas** [comment]
@fmendezh is the DataONE repo in a position to serve as the consistent resting place for archival versions of documentation?

**Comment by kcopas** [comment]
Previous version posted to Zenodo (in all four available languages) and redirected through the GBIF DOI:
http://doi.org/10.15468/doc.fm4b-6q42
