### ISSUE TITLE
Produce art for boxes 4 & 6

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-effective-nodes-guidance#19]
Art produced in Illustrator, but text will also need to be translatable, so create English source files as text for inclusion in translation po file (whether CrowdIn or other).

**Comment by kcopas** [comment]
Box 4 done, box 6 to come

**Comment by kcopas** [comment]
@melianieraymond could you point me to the highest-resolution version of this artwork?

![Screenshot 2020-01-09 at 16 05 46](https://user-images.githubusercontent.com/12379236/72078749-f9f43c80-32f9-11ea-9016-b239dd9df7a8.png)

**Comment by kcopas** [comment]
Artwork for Box 5 still in progress. No need to further delay translation updates while waiting to resolve, per discussion with @melianieraymond

**Comment by MattBlissett** [comment]
The Asciidoctor/HTML version I made last year has been translated into Spanish on Crowdin and works fine: https://docs.gbif-uat.org/effective-nodes-guidance/1.0/es/#box-6
