### ISSUE TITLE
Edit last paragraph in §1?

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-effective-nodes-guidance#2]
Consider changing emphasis of last paragraph in Section 1 ["Participant nodes provide the technical expertise…"] from informatics infrastructure towards providing access to tools

**Comment by kcopas** [comment]
See https://docs.gbif-uat.org/effective-nodes-guidance/1.0/en/#introduction. I'm not sure this one's been resolved.

**Comment by melianieraymond** [comment]
I think this one is fine as it is
