### ISSUE TITLE
Add link to guiding examples in §4

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-effective-nodes-guidance#3]
Discuss with Kyle best way of linking to the guiding examples here.

**Comment by kcopas** [comment]
[Link](https://www.gbif.org/resource/search?q=%22Nodes%20guidance%22) added in §7, but looking back at the Google doc, the reference/suggestion in §4 was more general.

@melianieraymond do you recall whether you wanted to link specific examples or have a single link to the lot of the guiding examples.

@dnoesgaard has shown that we can hack our way to a search result, though we hope to have a curated landing page in the not-too-distant future.

**Comment by melianieraymond** [comment]
I think it would be good to have a link to all the guiding examples in 7. We don't really need one in 4 I don't think

**Comment by kcopas** [comment]
Okay, we're good for now. We should be able to improve upon the [starter link](https://www.gbif.org/resource/search?q=%22Nodes%20guidance%22)'s accuracy shortly…
